<?php
namespace gamboamartin\administrador\models;

use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class adm_menu extends modelo{
    public function __construct(PDO $link){
        $tabla = 'adm_menu';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array('etiqueta_label');

        $columnas_extra['adm_menu_n_secciones'] = /** @lang sql */
            "(SELECT COUNT(*) FROM adm_seccion WHERE adm_seccion.adm_menu_id = adm_menu.id)";

        parent::__construct(link: $link,tabla:  $tabla,campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra);
        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|stdClass
    {
        if(!isset($this->registro['etiqueta_label'])){
            $etiqueta_label = $this->registro['descripcion'];
            $etiqueta_label = str_replace('_', ' ', $etiqueta_label);
            $etiqueta_label = ucwords($etiqueta_label);
            $this->registro['etiqueta_label'] = $etiqueta_label;
        }
        if(!isset($this->registro['icono'])){
            $icono = 'SI';
            $this->registro['icono'] = $icono;
        }
        if(!isset($this->registro['observaciones'])){
            $observaciones = 'SO';
            $this->registro['observaciones'] = $observaciones;
        }


        $registro = $this->codigo_default(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al generar codigo',data: $registro);
        }

        $this->registro = $registro;


        if(!isset($this->registro['codigo_bis'])){
            $codigo_bis = $this->registro['codigo'];
            $this->registro['codigo_bis'] = $codigo_bis;
        }

        if(!isset($this->registro['descripcion_select'])){
            $descripcion_select = $this->registro['codigo'].' '.$this->registro['descripcion'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if(!isset($this->registro['alias'])){
            $alias = strtoupper($this->registro['descripcion']);
            $this->registro['alias'] = $alias;
        }


        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta adm_menu',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }

    private function codigo_alta_default(string $adm_menu_descripcion): array|string
    {
        return ' '.$adm_menu_descripcion;
    }

    private function codigo_default(array $registro): array
    {
        $valida = $this->valida_alta_bd(registro:$registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data: $valida);
        }

        if(!isset($registro['codigo'])){

            $codigo = $this->codigo_alta_default(adm_menu_descripcion:  $registro['descripcion']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al generar codigo',data: $codigo);
            }
            $registro['codigo'] = $codigo;
        }
        return $registro;
    }

    /**
     * Obtiene las secciones de un menu
     * @param int $adm_menu_id Menu identificador
     * @return array
     * @version 0.545.51
     */
    public function secciones(int $adm_menu_id): array
    {
        if($adm_menu_id <= 0){
            return $this->error->error(mensaje: 'Error adm_menu_id debe ser mayor a 0',data:  $adm_menu_id);
        }
        $filtro['adm_menu.id'] = $adm_menu_id;
        $r_adm_seccion = (new adm_seccion($this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener secciones',data:  $r_adm_seccion);
        }
        return $r_adm_seccion->registros;
    }

    private function valida_alta_bd(array $registro): bool|array
    {

        $keys = array('descripcion');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data: $valida);
        }
        return true;
    }
}