<?php
namespace gamboamartin\administrador\models;

use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class adm_accion_basica extends modelo{
    public function __construct(PDO $link){
        $tabla = 'adm_accion_basica';
        $columnas = array($tabla=> false);
        $campos_obligatorios=array('descripcion','codigo','codigo_bis','visible','seguridad','inicio','lista',
            'status','es_view','descripcion_select','etiqueta_label','es_modal','titulo','css','es_status','alias',
            'es_lista');
        parent::__construct(link: $link,tabla:  $tabla,campos_obligatorios: $campos_obligatorios, columnas: $columnas);
        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|stdClass
    {

        if(!isset($this->registro['codigo_bis'])){
            $codigo_bis = $this->registro['codigo'];
            $codigo_bis .= ' '.$this->registro['descripcion'];
            $this->registro['codigo_bis'] = $codigo_bis;
        }
        if(!isset($this->registro['visible'])){
            $this->registro['visible'] = 'inactivo';
        }
        if(!isset($this->registro['seguridad'])){
            $this->registro['seguridad'] = 'inactivo';
        }
        if(!isset($this->registro['inicio'])){
            $this->registro['inicio'] = 'inactivo';
        }
        if(!isset($this->registro['lista'])){
            $this->registro['lista'] = 'inactivo';
        }
        if(!isset($this->registro['es_view'])){
            $this->registro['es_view'] = 'inactivo';
        }
        if(!isset($this->registro['descripcion_select'])){
            $descripcion_select = $this->registro['descripcion'];
            $descripcion_select .= ' '.$this->registro['codigo'];
            $this->registro['descripcion_select'] = $descripcion_select;
        }
        if(!isset($this->registro['etiqueta_label'])){
            $etiqueta_label = str_replace('_', ' ', $this->registro['descripcion']);
            $etiqueta_label = ucwords($etiqueta_label);

            $this->registro['etiqueta_label'] = $etiqueta_label;
        }
        if(!isset($this->registro['es_modal'])){
            $this->registro['es_modal'] = 'inactivo';
        }
        if(!isset($this->registro['titulo'])){

            $this->registro['titulo'] = $this->registro['etiqueta_label'] ;
        }
        if(!isset($this->registro['css'])){
            $this->registro['css'] = 'info';
        }
        if(!isset($this->registro['es_status'])){
            $this->registro['es_status'] = 'inactivo';
        }
        if(!isset($this->registro['alias'])){
            $alias = strtoupper($this->registro['descripcion']);
            $this->registro['alias'] = $alias;
        }
        if(!isset($this->registro['es_lista'])){
            $this->registro['es_lista'] = 'inactivo';
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar accion basica',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }
}
