<?php
namespace gamboamartin\administrador\models;

use base\orm\inicializacion;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class adm_accion_basica extends modelo{
    public function __construct(PDO $link){
        $tabla = 'adm_accion_basica';
        $columnas = array($tabla=> false);
        $campos_obligatorios=array('descripcion','codigo','codigo_bis','visible','seguridad','inicio','lista',
            'status','es_view','descripcion_select','etiqueta_label','es_modal','titulo','css','es_status','alias',
            'es_lista');

        $no_duplicados[] = 'descripcion';
        parent::__construct(link: $link,tabla:  $tabla,campos_obligatorios: $campos_obligatorios, columnas: $columnas,
            no_duplicados: $no_duplicados);
        $this->NAMESPACE = __NAMESPACE__;
    }

    private function alias(array $registro): string
    {
        return strtoupper($registro['descripcion']);
    }

    public function alta_bd(): array|stdClass
    {
        $registro = $this->init_alta_bd(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar registro',data: $registro);
        }
        $this->registro = $registro;

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar accion basica',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


    private function css(): string
    {
        return 'info';
    }

    /**
     * Obtiene un codigo bid de accion
     * @param array $registro $registro en proceso de alta bd
     * @return string|array
     * @version 2.13.2.3
     */
    private function codigo_bis(array $registro): string|array
    {
        $keys = array('codigo','descripcion');
        $valida = $this->validacion->valida_existencia_keys(keys:$keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data: $valida);
        }
        $codigo_bis = $registro['codigo'];
        $codigo_bis .= ' '.$registro['descripcion'];
        return $codigo_bis;
    }

    private function descripcion_select(array $registro): string
    {
        $descripcion_select = $registro['descripcion'];
        $descripcion_select .= ' '.$registro['codigo'];
        return $descripcion_select;
    }

    private function etiqueta_label(array $registro): string
    {
        $etiqueta_label = str_replace('_', ' ', $registro['descripcion']);
        return ucwords($etiqueta_label);
    }


    private function init_alias(array $registro): array
    {
        if(!isset($registro['alias'])){

            $alias = $this->alias(registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera alias',data: $alias);
            }
            $registro['alias'] = $alias;
        }
        return $registro;
    }

    private function init_alta_bd(array $registro): array
    {
        $registro = $this->init_alta_bd_base(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar registro',data: $registro);
        }

        $registro = $this->init_statuses_alta(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializa status',data: $registro);
        }

        return $registro;
    }

    private function init_alta_bd_base(array $registro): array
    {
        $registro = $this->init_codigo_bis(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera codigo bis',data: $registro);
        }

        $registro = $this->init_descripcion_select(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera descripcion_select',data: $registro);
        }

        $registro = $this->init_etiqueta_label(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera etiqueta_label',data: $registro);
        }

        $registro = $this->init_titulo(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera titulo',data: $registro);
        }

        $registro = $this->init_css(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera css',data: $registro);
        }


        $registro = $this->init_alias(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al genera alias',data: $registro);
        }
        return $registro;
    }

    private function init_css(array $registro): array
    {
        if(!isset($registro['css'])){
            $css = $this->css();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera css',data: $css);
            }

            $registro['css'] = $css;
        }
        return $registro;
    }

    private function init_codigo_bis(array $registro): array
    {
        if(!isset($registro['codigo_bis'])){

            $codigo_bis = $this->codigo_bis(registro:$registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera codigo bis',data: $codigo_bis);
            }
            $registro['codigo_bis'] = $codigo_bis;
        }
        return $registro;
    }

    private function init_descripcion_select(array $registro): array
    {
        if(!isset($registro['descripcion_select'])){

            $descripcion_select = $this->descripcion_select(registro:$registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera descripcion_select',data: $descripcion_select);
            }
            $registro['descripcion_select'] = $descripcion_select;
        }
        return $registro;
    }

    private function init_etiqueta_label(array $registro): array
    {
        if(!isset($registro['etiqueta_label'])){

            $etiqueta_label = $this->etiqueta_label(registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera etiqueta_label',data: $etiqueta_label);
            }

            $registro['etiqueta_label'] = $etiqueta_label;
        }
        return $registro;
    }


    private function init_statuses_alta(array $registro): array
    {
        $keys_statuses = array('es_lista','es_modal','es_status','es_view','inicio','lista','seguridad','visible');

        $registro = (new inicializacion())->inicializa_statuses(keys: $keys_statuses, registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializa status',data: $registro);
        }
        return $registro;
    }

    private function init_titulo(array $registro): array
    {
        if(!isset($registro['titulo'])){
            $titulo = $this->titulo(registro:$registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al genera titulo',data: $titulo);
            }
            $registro['titulo'] = $titulo;
        }
        return $registro;
    }

    private function titulo(array $registro){
        return $registro['etiqueta_label'];
    }
}
