<?php
namespace gamboamartin\administrador\models;


use base\orm\_modelo_parent_sin_codigo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class adm_tipo_dato extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'adm_tipo_dato';
        $columnas = array($tabla=>false);
        parent::__construct(link: $link, tabla: $tabla,columnas: $columnas);
        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        if(isset($this->registro['codigo_bis'])){
            unset($this->registro['codigo_bis']);
        }
        $r_alta =  parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta',data:  $r_alta);
        }
        return $r_alta;
    }
}