<?php
namespace models;
use base\orm\modelo;


use gamboamartin\errores\errores;
use PDO;
use stdClass;

class adm_seccion_pertenece extends modelo{
    /**
     * DEBUG INI
     * @param PDO $link
     */
    public function __construct(PDO $link){
        $tabla = __CLASS__;
        $columnas = array($tabla=>false, 'adm_seccion'=>$tabla,'adm_sistema'=>$tabla,'adm_menu'=>'adm_seccion');
        $campos_obligatorios = array('adm_seccion_id','adm_sistema_id');
        parent::__construct(link: $link,tabla:  $tabla,campos_obligatorios: $campos_obligatorios,columnas:  $columnas);
    }

    public function alta_bd(): array|stdClass
    {

        $keys = array('adm_seccion_id','adm_sistema_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }

        $adm_seccion = (new adm_seccion(link: $this->link))->registro(
            registro_id: $this->registro['adm_seccion_id'], columnas_en_bruto: true, retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener seccion', data: $adm_seccion);
        }
        $adm_sistema = (new adm_sistema(link: $this->link))->registro(
            registro_id: $this->registro['adm_sistema_id'], columnas_en_bruto: true, retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener seccion', data: $adm_seccion);
        }

        if(!isset($this->registro['codigo'])){

            $codigo = $adm_seccion->codigo.' '.$adm_sistema->codigo;
            $this->registro['codigo'] = $codigo;
        }
        if(!isset($this->registro['descripcion'])){

            $descripcion = $adm_seccion->descripcion.' '.$adm_sistema->descripcion;
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd =  parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar seccion pertenece', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


}