<?php
namespace base\orm;


use gamboamartin\errores\errores;
use stdClass;

class _modelo_parent extends _base {

    public function alta_bd(array  $keys_integra_ds = array('codigo','descripcion')): array|stdClass
    {
        $this->registro = $this->campos_base(data:$this->registro,modelo: $this, keys_integra_ds: $keys_integra_ds);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar campo base',data: $this->registro);
        }

        $r_alta_bd =  parent::alta_bd();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo','descripcion')): array|stdClass
    {

        $registro = $this->campos_base(data: $registro, modelo: $this, id: $id,keys_integra_ds:$keys_integra_ds );
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar campo base',data: $registro);
        }

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar cp',data:  $r_modifica_bd);
        }

        return $r_modifica_bd;
    }

    private function alta_predeterminado(){
        $pred_ins['predeterminado'] = 'activo';
        $pred_ins['codigo'] = 'PRED';
        $pred_ins['descripcion'] = 'PREDETERMINADO';
        $r_alta = $this->alta_registro(registro: $pred_ins);
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al insertar prederminado',data:  $pred_ins);
        }
        return $r_alta;
    }

    protected function inserta_predeterminado(){
        $r_pred = new stdClass();
        $existe = $this->existe_predeterminado();
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al validar si existe predeterminado',data:  $existe);
        }
        if(!$existe){
            $r_pred = $this->alta_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al insertar prederminado',data:  $r_pred);
            }
        }
        return $r_pred;
    }


}
